[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "main.settings"

addopts = "--disable-warnings --reuse-db"
python_files = [
    "test_*.py",
    "*_test.py",
    "testing/python/*.py",
    ]


[tool.ty.rules]

unresolved-attribute = "ignore"
